account/urls.py
from django.urls import path
from .views import *

app_name="account"

urlpatterns = [
    path('register', register_page,name="register"),
    path('login', login_page,name="login"),
    path('logout', logout_page,name="logout"),

]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from cars.views import *

urlpatterns = [
    path('', car_page,name="home"),
    path('updatecar/<int:id>', update_car,name="update"),
    path('deletecar/<int:id>', delete_car,name="delete"),
    path('addcar', add_car,name="add"),
    path('mycar', my_car_page,name="mycar"),
    path('cardetail/<int:id>', car_detail,name="cardetail"),
    path('comment/<int:id>', add_comment,name="comment"),
    path('about', about_page,name="about"),
    path('contact', contact_page,name="contact"),
    path('account/', include("account.urls")),
    path('admin/', admin.site.urls),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

cars/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Cars(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE)
    marka = models.CharField(max_length = 150)
    model = models.CharField(max_length = 150)
    description = RichTextField()
    added_date = models.DateTimeField( auto_now_add=True)
    photo = models.FileField(upload_to='photo',blank=True,null=True)

class Comment(models.Model):
    author=models.ForeignKey("auth.User",on_delete=models.CASCADE)
    car=models.ForeignKey(Cars,on_delete=models.CASCADE,verbose_name="masin",related_name="comments")
    comment_content=RichTextField()
    added_date = models.DateTimeField( auto_now_add=True)

    def __str__(self):
        return f"{self.comment_content}"



    
    
    

account/forms.py
from typing import Any
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 30,label="Username")
    password = forms.CharField(max_length = 10,label="Password",widget=forms.PasswordInput)
    confirm= forms.CharField(max_length = 10,label="Confirm pasword",widget=forms.PasswordInput)

    def clean(self):
        username=self.cleaned_data["username"]
        password=self.cleaned_data["password"]
        confirm=self.cleaned_data["confirm"]

        if username and password and password != confirm:
            raise forms.ValidationError("sifreler duz deil")
        values={
            "username":username,
            "password":password
        }

        return values
        

class LoginForm(forms.Form):
    username = forms.CharField(max_length = 30,label="Username")
    password = forms.CharField(max_length = 10,label="Password",widget=forms.PasswordInput)

    
   

    

account/views.py
from django.shortcuts import render,redirect
from  .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
# Create your views here.
def register_page(request):

 
    form=RegisterForm(request.POST or None)

    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")

        newUser=User(username=username)
        newUser.set_password(password)
        newUser.save()

        login(request,newUser)
        messages.success(request,"ugurla qeydiyatdan kecdiniz")

        return redirect("home")


    context={
        "form":form
    }


    return render(request,"register.html",context)


def login_page(request):
    form=LoginForm(request.POST or None )
    context={
        "form":form
    }

    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")

        user =authenticate(username=username,password=password)
        if user is None:
            render(request,"login.html")

        login(request,user)
        messages.success(request,"ugurla qeydiyatdan kecdiniz")
        return redirect("home")
    

    return render(request,"login.html",context)


def logout_page(request):
    logout(request)
    messages.warning(request,"cixis etdiniz")
    return redirect("home")

cars/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse
from .models import Cars,Comment
from .form import CarForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def car_page(request):
    cars=Cars.objects.all()
    marka=request.GET.get("marka")
    model=request.GET.get("model")
    if marka or model:
        cars=Cars.objects.filter(model__contains=model ,marka__contains=marka)
        return render(request,'cars.html',{'cars':cars})
    return render(request,'cars.html',{'cars':cars})

@login_required(login_url="account:login")
def my_car_page(request):
    cars=Cars.objects.filter(author=request.user)
    return render(request,'mycar.html',{'cars':cars})

def about_page(request):
    return render(request,"about.html")
# Create your views here.
def contact_page(request):
    return render(request,"contact.html")

@login_required(login_url="account:login")
def add_car(request):
    form=CarForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        car=form.save(commit=False)
        car.author=request.user
        car.save()
        messages.success(request,"islem basarili")
        return redirect("mycar")

    context={
        "form":form
    }
    return render(request,"addcar.html",context)

@login_required(login_url="account:login")
def update_car(request,id):
    car=get_object_or_404(Cars,id=id)
    form=CarForm(request.POST or None,request.FILES or None,instance=car)

    if form.is_valid():
        car=form.save(commit=False)
        car.author=request.user
        car.save()
        messages.success(request,"islem basarili")
        return redirect("mycar")

    context={
        "form":form
    }
    return render(request,"update.html",context)

@login_required(login_url="account:login")
def delete_car(request,id):
      car=get_object_or_404(Cars,id=id)
      car.delete()
      messages.success(request,"islem basarili")
      return redirect("mycar")



def car_detail(request,id):
    # car=Cars.objects.filter(id=id).first()
    
    car=get_object_or_404(Cars,id=id)
    comments=Comment.objects.filter(car=car)
    context={
        "car":car,
        "comments":comments
    }
    return render(request,"cardetail.html",context)



@login_required(login_url="account:login")
def add_comment(request,id):
    car=get_object_or_404(Cars,id=id)
    if request.method=="POST":
        comment_content=request.POST.get("comment_content")
        newComment= Comment(comment_content=comment_content)
        newComment.car=car
        newComment.author=request.user
        newComment.save()
        messages.success(request,"islem basarili")
    return redirect(reverse("cardetail",kwargs={"id":id}))

templates/about.html
{% extends 'base.html' %}

{% block body %}
    <h1>about page</h1>
{% endblock %}

templates/addcar.html
{% extends 'base.html' %}


{% block body %}
   <h1>Add car</h1> 
    <form method="post">
        {% csrf_token %}
        {{form.media}}
      
        <div class="form_group">
            <label for="{{form.marka.id_for_label}}">Marka adi</label>
            {{form.marka}}
        </div>
        <div class="form_group">
            <label for="{{form.model.id_for_label}}">Model adi</label>
            {{form.model}}
        </div>
        <div class="form_group">
            <label for="{{form.description.id_for_label}}">tasvir et</label>
            {{form.description}}
        </div>
        <div class="form_group">
            <label for="{{form.photo.id_for_label}}">Sekil yukle</label>
            {{form.photo}}
        </div>

        <button class="btn">Add</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <title>Document</title>
</head>
<body>
    
         <div class="navbar">
       
        <div class="navbar_logo">
            <img src="{% static '1.png '%}" alt="photo">
        </div>
        <div class="nav_links">
            <ul>
                <li><a href="{% url 'home' %}">Cars</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'contact'  %}">Contact</a></li>
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'mycar' %}">My Cars</a></li>
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
                {%else%}
                   <li><a href="{% url 'account:register' %}">Register</a></li>
                <li><a href="{% url 'account:login' %}">Login</a></li>   
                {% endif %}
              
               
            </ul>
        </div>
      
    </div>
   <div class="container">
     {% block body %}
        
    {% endblock %}
   </div>
   <script src="{% static 'app.js' %}"></script>
</body>
</html>

templates/cardetail.html
{% extends 'base.html' %}

{% block body %}

{% if messages %}

{% for message in messages %}

{% if message.tags == "warning" %}
<div id="message" class="alert_warning">
   <span>   {{message}} </span>
</div>
{% else %}
<div id="message" class="alert_success">
   <span>{{message}}</span> 
</div>
{% endif %}
    
{% endfor %}
    
{% endif %}

    Detail
   
    <div>

        <h3>{{car.marka}}</h3>
        <h4>{{car.model}}</h4>
        <p>{{car.description|safe}}</p>
        {% if car.photo %}
        <img src="{{car.photo.url}}" alt="">
      
        {% endif %}
       
       
        
    </div>

    <div class="cooments">
        <h3>sehrler</h3>
        {% if comments %}
        {% for comment in comments %}
            <p>{{comment.author}} {{comment.comment_content|safe}} commentini {{comment.added_date}} de paylasdi</p>
        <hr>
            {% endfor %}
       
            
        {% else %}
        <p>sehr yoxdur</p>
        {% endif %}
    </div>

    <div class="comment_form">
        <form action="{% url 'comment' car.id %}" method="post">

            {% csrf_token %}

            <div class="form_group">
               <textarea type="text" rows="10" cols="50" name="comment_content" placeholder="Sehriniz"></textarea>
            </div>

        <button type="submit">paylas</button>    
        </form>
    </div>
    
 
{% endblock %}

templates/cars.html
{% extends 'base.html' %}

{% block body %}

{% if messages %}

{% for message in messages %}

{% if message.tags == "warning" %}
<div id="message" class="alert_warning">
   <span>   {{message}} </span>
</div>
{% else %}
<div id="message" class="alert_success">
   <span>{{message}}</span> 
</div>
{% endif %}
    
{% endfor %}
    
{% endif %}


   <h1>Arabalar</h1>
   <div class="search_form">
      <form action="">
         {% csrf_token %}
         <input name="marka" type="text" placeholder="marka ...">
         <input name="model" type="text" placeholder="model ...">

         <button type="submit">axtar</button>
      </form>
   </div>



   {% if cars %}
   {% for car in cars %}
    <div>

        <h3>{{car.marka}}</h3>
        <h4>{{car.model}}</h4>
        <p>{{car.description|safe |truncatechars:10 }}</p>
        {% if car.photo %}
        <img src="{{car.photo.url}}" alt="">
      
        {% endif %}
       
      
        
        <a href="{% url 'cardetail' car.id %}"><button>Detail</button></a>
    </div>
   {% endfor %}
      
   {% else %}
   <p> Elan yoxdur</p>
      
   {% endif %}

   


{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block body %}
    <h1>Contaxt page</h1>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block body %}
    <h1 style="text-align: center;">login </h1>
    <form method="post">
        {%  csrf_token %}
        <div class="form_group">
            <label for="{{form.username.id_for_label}}">istifadeci adi</label>
            {{form.username}}
        </div>
        <div class="form_group">
            <label for="{{form.password.id_for_label}}">password</label>
            {{form.password}}
        </div>
        <button class="btn">ok</button>
    </form>
{% endblock %}

templates/mycar.html
{% extends 'base.html' %}

{% block body %}


{% if messages %}

{% for message in messages %}

{% if message.tags == "warning" %}
<div id="message" class="alert_warning">
   <span>   {{message}} </span>
</div>
{% else %}
<div id="message" class="alert_success">
   <span>{{message}}</span> 
</div>
{% endif %}
    
{% endfor %}
    
{% endif %}





<h1>Menim masinlarim</h1>
{% for car in cars %}
 <div>

     <h3>{{car.marka}}</h3>
     <h4>{{car.model}}</h4>
     <p>{{car.description|safe}}</p>
     <a href="{% url 'update' car.id %}">guncelle</a>
     <a href="{% url 'delete' car.id %}">delete</a>
 </div>
{% endfor %}
<a href="{% url 'add' %}"><button class="btn">Yeni Masin elave et</button></a>

    
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block body %}
    <h1 style="text-align: center;">Register </h1>

    <form method="post">
        {%  csrf_token %}
        <div class="form_group">
            <label for="{{form.username.id_for_label}}">istifadeci adi</label>
            {{form.username}}
        </div>

        <div class="form_group">
            <label for="{{form.password.id_for_label}}">password</label>
            {{form.password}}
        </div>

        <div class="form_group">
            <label for="{{form.confirm.id_for_label}}">Confirm</label>
            {{form.confirm}}
        </div>

        <button class="btn">qeydiyyatda kec</button>
    </form>
{% endblock %}

templates/update.html
{% extends 'base.html' %}


{% block body %}
   <h1>Update car</h1> 
    <form method="post">
        {% csrf_token %}
        {{form.media}}
      
        <div class="form_group">
            <label for="{{form.marka.id_for_label}}">Marka adi</label>
            {{form.marka}}
        </div>
        <div class="form_group">
            <label for="{{form.model.id_for_label}}">Model adi</label>
            {{form.model}}
        </div>
        <div class="form_group">
            <label for="{{form.description.id_for_label}}">tasvir et</label>
            {{form.description}}
        </div>
        <div class="form_group">
            <label for="{{form.photo.id_for_label}}">Sekil yukle</label>
            {{form.photo}}
        </div>

        <button class="btn">Update</button>
    </form>
{% endblock %}